// Generated by scripts/generate-icons-list.mjs
export default [
    "add",
    "add_comment",
    "apps",
    "bedtime",
    "bedtime_off",
    "cancel",
    "change_circle",
    "check",
    "close",
    "code",
    "comment",
    "content_copy",
    "delete_forever",
    "edit",
    "rate_review",
    "settings",
    "undo"
];
